const sections = [
  ['Information We Collect','We may collect personal information such as your name, phone number, email address, and any other details submitted through enquiry forms on this website.'],
  ['How We Use Information','Your information may be used to respond to enquiries, share project updates, schedule site visits, provide brochures, and improve customer communication related to the project.'],
  ['Information Sharing','We may share submitted information with authorized marketing partners, developers, CRM systems, or RERA-registered channel partners strictly for business communication and follow-up purposes.'],
  ['Cookies and Tracking','This website may use cookies, analytics tools, pixels, and similar technologies to understand visitor behavior, improve campaigns, and optimize website performance.'],
  ['Data Security','Reasonable administrative and technical safeguards are used to protect the information submitted on this website. However, no internet transmission or storage system can be guaranteed to be fully secure.'],
  ['Third-Party Links','This website may contain links to third-party websites. We are not responsible for the content, privacy practices, or security of such external websites.'],
  ['Consent','By using this website and submitting your details, you consent to the collection and use of information in accordance with this privacy policy and the applicable terms and conditions.'],
  ['Policy Updates','This privacy policy may be updated from time to time without prior notice. Please review this page periodically to stay informed of any changes.']
]
export function PrivacyPolicy(){return <main className="bg-[#fbf8f3] pt-16"><section className="bg-[#11110f] px-5 py-20 text-white md:px-10"><div className="container"><p className="eyebrow">Legal information</p><h1 className="display text-5xl md:text-6xl">Privacy Policy</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">How information collected through the Rustomjee 180 Bayview website is handled.</p></div></section><section className="container grid gap-12 px-5 py-16 md:grid-cols-[1.3fr_.7fr] md:px-10 md:py-24"><div className="space-y-9">{sections.map(([title,copy])=><article key={title}><h2 className="display text-3xl">{title}</h2><p className="mt-3 text-sm leading-7 text-stone-700">{copy}</p></article>)}<article className="border-t border-stone-300 pt-9"><h2 className="display text-3xl">Disclaimer</h2><p className="mt-3 text-sm leading-7 text-stone-700">The content presented on this website is solely for informational purposes and does not constitute a service offer. Prices mentioned here are subject to change without prior notification, and the availability of the listed properties is not assured. Images showcased are illustrative and may not precisely represent the actual properties.</p><p className="mt-4 text-sm leading-7 text-stone-700">This website operates as an authorized marketing partner, True Value Home. For necessary processing, we may share data with Real Estate Regulatory Authority (RERA) registered brokers or companies. Updates and information may be sent to the registered mobile number or email ID. All rights reserved. This website’s content, design, and data are protected by copyright and other intellectual-property rights. For precise and current information on services, pricing, availability, or any other details, please contact us directly through the contact information on this website.</p></article></div><aside className="h-fit border border-[#c8a15a]/40 bg-white p-7 shadow-luxury md:sticky md:top-24"><p className="eyebrow">Project registration</p><h2 className="display text-3xl">Rustomjee 180 Bayview</h2><p className="mt-5 text-sm leading-7 text-stone-700">This project is RERA registered and registered under MahaRERA.</p><dl className="mt-6 space-y-4 border-y border-stone-200 py-5 text-sm"><div><dt className="text-[10px] font-bold uppercase tracking-widest text-gold">Agent RERA Number</dt><dd className="mt-1 font-semibold">A51600047463</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-widest text-gold">Project RERA Number</dt><dd className="mt-1 font-semibold">P51900066547 | P51900066548</dd></div></dl><a className="btn-gold mt-6 w-full !bg-[#c8a15a] !text-[#11110f]" href="https://maharera.maharashtra.gov.in/" target="_blank" rel="noreferrer">View MahaRERA website</a></aside></section></main>}
