import { AnimatePresence, motion, useSpring } from 'framer-motion'
import { useEffect, useState } from 'react'

export function Experience(){
  const [loaded,setLoaded]=useState(false); const [progress,setProgress]=useState(0); const [cursor,setCursor]=useState({x:-100,y:-100}); const [hover,setHover]=useState(false)
  const smoothX=useSpring(cursor.x,{stiffness:500,damping:38,mass:.35}); const smoothY=useSpring(cursor.y,{stiffness:500,damping:38,mass:.35})
  useEffect(()=>{const done=window.setTimeout(()=>setLoaded(true),700); const scroll=()=>{const height=document.documentElement.scrollHeight-window.innerHeight;setProgress(height?window.scrollY/height:0)}; const move=(event:MouseEvent)=>setCursor({x:event.clientX,y:event.clientY}); const over=(event:MouseEvent)=>{const target=event.target as Element;setHover(Boolean(target.closest('a,button,input,select')))}; scroll();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('mousemove',move);document.addEventListener('mouseover',over);return()=>{window.clearTimeout(done);window.removeEventListener('scroll',scroll);window.removeEventListener('mousemove',move);document.removeEventListener('mouseover',over)}},[])
  return <><motion.div aria-hidden="true" className="fixed inset-x-0 top-0 z-[100] h-[2px] origin-left bg-gold" style={{scaleX:progress}}/><motion.div aria-hidden="true" className="pointer-events-none fixed left-0 top-0 z-[100] hidden h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-gold mix-blend-difference lg:block" animate={{width:hover?36:20,height:hover?36:20}} style={{x:smoothX,y:smoothY}}/><AnimatePresence>{!loaded&&<motion.div initial={{opacity:1}} exit={{opacity:0,transition:{duration:.45}}} className="fixed inset-0 z-[120] grid place-items-center bg-ink text-white"><motion.div initial={{opacity:0,y:20,letterSpacing:'0.05em'}} animate={{opacity:1,y:0,letterSpacing:'.18em'}} transition={{duration:.6}} className="display text-2xl">RUSTOMJEE <span className="text-gold">180 BAYVIEW</span></motion.div></motion.div>}</AnimatePresence></>
}
