import { useEffect, useState } from 'react'
import { CalendarDays, Menu, MessageCircle, Phone, X } from 'lucide-react'
import { trackEvent } from '../utils/tracking'
const whatsapp = 'https://wa.me/917030187000?text=Hello%2C%20I%20am%20interested%20in%20Rustomjee%20180%20Bayview.%20Please%20share%20brochure%2C%20pricing%20and%20available%20inventory.'
export const whatsappUrl = whatsapp
const navigation = [['Overview','#overview'],['Residences','#residences'],['Floor Plans','#residences'],['Amenities','#amenities'],['Gallery','#gallery'],['Location','#location'],['FAQs','#faqs']]
export function Header({ onEnquire }: { onEnquire: () => void }) {
  const [scrolled,setScrolled]=useState(false); const [open,setOpen]=useState(false)
  const onHomePage = window.location.pathname === '/'
  const route = (anchor: string) => onHomePage ? anchor : `/${anchor}`
  useEffect(()=>{const update=()=>setScrolled(window.scrollY>24);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[])
  const enquire=()=>{setOpen(false);trackEvent('site_visit_click');onEnquire()}
  return <header className={`fixed inset-x-0 top-0 z-40 border-b text-white transition-all duration-500 ${scrolled?'border-white/10 bg-ink/90 shadow-xl backdrop-blur-xl':'border-transparent bg-ink/45 backdrop-blur-sm'}`}><div className="container flex h-16 items-center justify-between px-5 md:px-10"><a href={route('#top')} className="display text-lg leading-none transition-transform duration-300 hover:scale-[1.03] sm:text-xl">RUSTOMJEE <span className="text-gold">180 BAYVIEW</span><small className="ml-1 font-sans text-[7px] tracking-[.18em] text-white/70">MATUNGA WEST</small></a><nav className="hidden items-center gap-5 text-[10px] font-bold uppercase tracking-[.12em] text-white/75 xl:flex">{navigation.map(([label,href])=><a key={label} className="nav-link" href={route(href)}>{label}</a>)}</nav><div className="flex items-center gap-1"><a onClick={()=>trackEvent('call_click')} href="tel:+917030187000" aria-label="Call us" className="hidden p-2 transition hover:scale-110 md:inline-flex"><Phone size={17}/></a><a onClick={()=>trackEvent('whatsapp_click')} href={whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp us" className="hidden p-2 text-gold transition hover:scale-110 md:inline-flex"><MessageCircle size={17}/></a><button onClick={enquire} className="btn-gold !bg-[#c8a15a] !px-3 !py-2.5 !text-[#11110f] text-[10px]"><CalendarDays size={14}/> <span className="hidden sm:inline">Book site visit</span><span className="sm:hidden">Enquire</span></button><button onClick={()=>setOpen(true)} aria-label="Open menu" className="p-2 xl:hidden"><Menu size={19}/></button></div></div>{open&&<div className="fixed inset-0 top-0 z-50 flex flex-col bg-[#11110f]/98 px-7 py-6 backdrop-blur-xl xl:hidden"><div className="flex items-center justify-between"><span className="display text-xl">RUSTOMJEE <span className="text-gold">180 BAYVIEW</span></span><button onClick={()=>setOpen(false)} aria-label="Close menu"><X size={24}/></button></div><nav className="mt-14 flex flex-col border-t border-white/10">{navigation.map(([label,href])=><a onClick={()=>setOpen(false)} key={label} href={route(href)} className="border-b border-white/10 py-5 text-sm font-bold uppercase tracking-[.16em] text-white/85">{label}</a>)}</nav><button onClick={enquire} className="btn-gold mt-8 !bg-[#c8a15a] !text-[#11110f]">Book a private site visit</button></div>}</header>
}
