import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Building, ChevronLeft, ChevronRight, Dumbbell, Flower2, Gamepad2, HeartPulse, LandPlot, LockKeyhole, MoonStar, PersonStanding, PersonStandingIcon, Sparkles, Trees, Waves } from 'lucide-react'
import { SectionHeading } from '../components/SectionHeading'
const data=[['Infinity Pool',Waves],['Clubhouse',Building],['Gym',Dumbbell],['Kids Play Area',Gamepad2],['Landscaped Gardens',Trees],['Multipurpose Hall',LandPlot],['Yoga Deck',PersonStanding],['Indoor Games',Gamepad2],['Sky Lounge',MoonStar],['Senior Citizen Area',HeartPulse],['Jogging Track',PersonStandingIcon],['24/7 Security',LockKeyhole]]
const amenityImages = [
  ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=82','Rooftop Infinity Pool','A serene, elevated setting for unhurried afternoons.'],
  ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=82','Resident Clubhouse','Spaces designed for connection, celebration and quiet escape.'],
  ['https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1600&q=82','Wellness Studio','A refined place to focus on movement and wellbeing.']
]
export function Amenities(){const [active,setActive]=useState(0);const next=()=>setActive(x=>(x+1)%amenityImages.length);const previous=()=>setActive(x=>(x-1+amenityImages.length)%amenityImages.length)
  useEffect(()=>{const timer=window.setInterval(next,5000);return()=>window.clearInterval(timer)},[])
  const [image,title,copy]=amenityImages[active]
  return <section id="amenities" className="section bg-[#171717] text-white"><div className="container"><SectionHeading eyebrow="Elevated everyday" title="Amenities for every version of your day." copy="A composed collection of places to reset, move, gather and simply be."/><div className="mt-12 grid grid-cols-2 border-l border-t border-white/10 sm:grid-cols-3 lg:grid-cols-4">{data.map(([text,Icon])=>{const I=Icon as typeof Sparkles;return <div className="border-b border-r border-white/10 p-5 md:p-7" key={text as string}><I size={23} className="text-gold"/><p className="mt-5 text-sm">{text as string}</p></div>})}</div><div className="mt-12 overflow-hidden border border-white/10"><div className="grid md:grid-cols-[1.35fr_.65fr]"><div className="relative min-h-72 overflow-hidden md:min-h-[390px]"><AnimatePresence mode="wait"><motion.img key={image} initial={{opacity:0,scale:1.06}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.98}} transition={{duration:.55}} loading="lazy" src={image} alt={title} className="absolute inset-0 h-full w-full object-cover"/></AnimatePresence></div><div className="flex flex-col justify-between p-7 md:p-10"><div><p className="eyebrow">Amenity gallery</p><AnimatePresence mode="wait"><motion.div key={title} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}><h3 className="display text-4xl">{title}</h3><p className="mt-5 max-w-xs text-sm leading-7 text-white/65">{copy}</p></motion.div></AnimatePresence></div><div className="mt-10 flex items-center justify-between"><div className="flex gap-2">{amenityImages.map((_,index)=><button onClick={()=>setActive(index)} aria-label={`Show slide ${index+1}`} key={index} className={`h-1.5 w-7 transition ${index===active?'bg-gold':'bg-white/25'}`}/>)}</div><div className="flex gap-2"><button onClick={previous} aria-label="Previous amenity" className="grid h-10 w-10 place-items-center border border-white/25 hover:border-gold hover:text-gold"><ChevronLeft size={18}/></button><button onClick={next} aria-label="Next amenity" className="grid h-10 w-10 place-items-center border border-white/25 hover:border-gold hover:text-gold"><ChevronRight size={18}/></button></div></div></div></div></div></div></section>}
